[funfacts]
title = "Wikipedia — did you know?"
url = "https://www.manoramaonline.com/children/parenting.html"
entrySelector = "#Children_Subsection_Parenting > div > ul > li > div"
titleSelector = "div.cmp-story-list__content > h2"
linkSelector = "div.cmp-story-list__content > h2 > a"

[wikivoyage]
title = "Wikivoyage recommendations"
url = "https://en.wikivoyage.org/wiki/Main_Page"
entrySelector = ".jcarousel-wrapper .jcarousel-item"
titleSelector = "h2"
linkSelector = "h2 a"
